// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQt9zIPGR_1Pbzx6LNmli8Wc3CF4W787U',
    appId: '1:436522470629:web:c9284ebeaddfb66b4cd80c',
    messagingSenderId: '436522470629',
    projectId: 'mynoteapp-bf4d9',
    authDomain: 'mynoteapp-bf4d9.firebaseapp.com',
    storageBucket: 'mynoteapp-bf4d9.appspot.com',
    measurementId: 'G-1C18D0H709',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABMwo760FZj1vToreWHuYO2WZE0qjy9DM',
    appId: '1:436522470629:android:b58895c5c1c614894cd80c',
    messagingSenderId: '436522470629',
    projectId: 'mynoteapp-bf4d9',
    storageBucket: 'mynoteapp-bf4d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdV8A1s9nWp-d5fUVlFAYybWDX_mVpTm4',
    appId: '1:436522470629:ios:1979b41e19211a414cd80c',
    messagingSenderId: '436522470629',
    projectId: 'mynoteapp-bf4d9',
    storageBucket: 'mynoteapp-bf4d9.appspot.com',
    iosBundleId: 'com.example.mynoteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdV8A1s9nWp-d5fUVlFAYybWDX_mVpTm4',
    appId: '1:436522470629:ios:1979b41e19211a414cd80c',
    messagingSenderId: '436522470629',
    projectId: 'mynoteapp-bf4d9',
    storageBucket: 'mynoteapp-bf4d9.appspot.com',
    iosBundleId: 'com.example.mynoteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQt9zIPGR_1Pbzx6LNmli8Wc3CF4W787U',
    appId: '1:436522470629:web:bd160c65718b142a4cd80c',
    messagingSenderId: '436522470629',
    projectId: 'mynoteapp-bf4d9',
    authDomain: 'mynoteapp-bf4d9.firebaseapp.com',
    storageBucket: 'mynoteapp-bf4d9.appspot.com',
    measurementId: 'G-ZB79N9PCCD',
  );
}
